version: 2
updates:
  - package-ecosystem: gomod
    open-pull-requests-limit: 2
    allow:
      - dependency-name: "git.vcc.live*"
  - package-ecosystem: gomod
    directory: ./
    open-security-pull-requests-limit: 5
    allow:
      - dependency-name: "*"

